---

- name: Create app-of-apps Application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'app-of-apps/app-of-apps-application.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: app_of_apps_result
  until: app_of_apps_result is not failed

- name: Print app_of_apps_result from the previous task
  ansible.builtin.debug:
    var: app_of_apps_result
