---

- name: Get OpenShift Ingress Domain
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_openshift_ingress

- name: Set user info for showroom
  agnosticd.core.agnosticd_user_info:
    data:
      common_password: "{{ common_password }}"
      openshift_cluster_ingress_domain: "{{ r_openshift_ingress.resources[0].spec.domain }}"
