---

- name: Create Terminal application
  when: ocp4_workload_platform_engineering_workshop_terminal_install | bool
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'terminal/terminal-subscription.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: terminal_result
  until: terminal_result is not failed

- name: Print terminal_result from the previous task
  ansible.builtin.debug:
    var: terminal_result
